services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    extra_hosts:
      - "nuxt-shadcn-node.localhost:127.0.0.1"
